config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users, controllers: { registrations: "users/registrations" }

  

  get '/admin', to: 'admin/home#index'

  namespace :admin do
    resources :users
    resources :games
    resources :teams
  end
  root "home#index"
  get "/contacto",to: "home#contact", as: 'contact'
  post "send_contact", to: "home#send_contact"
  get "/nosotros", to: "home#about", as: 'about'
  get "/servicios", to: "home#services", as: 'services'
  get "/torneos", to: "home#tournaments", as:'tournaments'
  get "/single", to: "home#single", as: 'single'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	before_filter :validate_admin
	layout "admin"
	def index
		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'simple', only: [:tournaments]

	def send_contact
		ContactMailer.send_contact(params[:name],params[:email],params[:number],params[:message]).deliver
	end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="col-lg-12 col-lg-offset-0" >
            <div class="row">
                <div class="box">
                		<h4>Duoc League of Gamers o "DLG", es una comunidad que se dedica a realizar eventos competitivos de videojuegos y tecnología. Nuestra organización se conforma por estudiantes mayormente de las escuelas de informática y salud. Aquí, luego de realizar exitosamente el primer evento DLG en Duoc, nace la idea y necesidad de desarrollar un software para sistematizar dichos procesos que nacen en la producción de eventos de esta categoría, como: Posicionamiento de stands (ventas u emprendimiento), elección de "cosplays", creación de brackets para competición de videojuegos, shows, etc. Nuestra misión es producir y facilitar la organización de las actividades de entretenimiento tecnológicas, mediante softwares construidos por nuestro propio equipo de informática. Nuestra visión es incentivar nacionalmente el mercado tecnológico y los deportes electrónicos. Por otro lado, también innovar en software de producción de eventos para grandes empresas. Junto con esto, empresas mundiales como "MSI" capta mayores ventas de sus productos y financia nuestros eventos. Hoy nos encontramos desarrollando nuestro software y plataforma web, la cual construirá una base de datos para ser utilizada con múltiples propósitos, principalmente organización y área de marketing (CRM). Recalcamos, nuestra misión de incentivar el entretenimiento electrónico y sus tecnologías, como; la sana competencia y la responsabilidad que lleva utilizar éstas herramientas. Hemos realizado ya dos eventos con éxito, esperando realizar el tercero y probar nuestro software con plataforma web. Nombre del software BETA: Zarit.</h4>
                </div>
            </div>
</div>            

app/views/home/contact.html.erb
<div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Contacto
                    
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
       
        <!-- /.row -->

        <!-- Contact Form -->
        <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
        
        <div class="col-lg-7 col-lg-offset-0" >
            <div class="row">
                <div class="box">
                    <h3>Escríbenos</h3>
                    <%= form_tag send_contact_path, method: "post" do %>
                        <div class="control-group form-group">
                            <div class="controls">
                                <label>Nombre Completo <span class="required">*</span></label>
                                <input name="name" type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                                <p class="help-block"></p>
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <label>Teléfono de contacto</label>
                                <input name="number" type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <label>Email <span class="required">*</span></label>
                                <input name="email" type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">
                                <label>Mensaje <span class="required">*</span></label>
                                <textarea name="message" rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                            </div>
                        </div>
                        <div id="success"></div>
                        <!-- For success/fail messages -->
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    <%end%>
                </div>

            </div>
        </div>
        <!-- /.row -->



        
</div>

app/views/home/index.html.erb
<div class="box colored tournament-partner">
    <div class="row">
        <div class="col-xs-4"><a href=""><img src="" class="img-responsive center-block" alt=""></a></div>
        <div class="col-sm-4"><a href="http://www.duoc.cl"><img src="assets/duoc.png" class="img-responsive center-block" alt=""></a></div>
        <div class="col-xs-4"><a href=""><img src="" class="img-responsive center-block" alt=""></a></div>
    </div>
</div>

<div class="box">

    <!-- POST - START -->
    <article class="post">
        <div class="post-date-wrapper">
            <div class="post-date">
                <div class="day">9</div>
                <div class="month">Nov 2014</div>
            </div>
            <div class="post-type">
                <i class="fa fa-video-camera"></i>
            </div>
        </div>
        <div class="post-body">
            <h2>DLG 2014</h2>
            <p><img src="/assets/image_005.jpg" class="img-responsive" alt="">En la primera version de Duoc League of Legends por parte del
            equipo de estudiantes quienes llevaron a cabo este evento junto con el apoyo de Duoc, se contemplaron torneos de Counter-Strike 1.6,
            League of Legends y un torneo de Cosplay.</p>
            <div class="post-info">
                <span>Posted by: admin</span>
                <a href="single.html" class="btn btn-inverse">View More</a>
            </div>
        </div>
    </article>
    <!-- POST - END -->
    
    <!-- POST - START --
    <article class="post">
        <div class="post-date-wrapper">
            <div class="post-date">
                <div class="day">25</div>
                <div class="month">Jan 2014</div>
            </div>
            <div class="post-type">
                <i class="fa fa-font"></i>
            </div>
        </div>
        <div class="post-body">
            <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et.</h2>
            <div class="flex-video widescreen"><iframe src="https://player.vimeo.com/video/48443133"></iframe></div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapibus ipsum eu, mattis urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapibus ipsum eu, mattis urna.</p>
            <div class="post-info">
                <span>Posted by: admin</span>
                <a href="single.html" class="btn btn-inverse">View More</a>
            </div>
        </div>
    </article>
    <!-- POST - END -->
    
    <!-- POST - START --
    <article class="post gallery-post">
        <div class="post-date-wrapper">
            <div class="post-date">
                <div class="day">25</div>
                <div class="month">Jan 2014</div>
            </div>
            <div class="post-type">
                <i class="fa fa-soundcloud"></i>
            </div>
        </div>
        <div class="post-body">
            <h2>Blog post with Gallery Carousel</h2>
            <div class="owl-carousel owl-theme">       
                    <div class="item"><img src="/assets/image_001.jpg" class="img-responsive" alt=""></div>
                    <div class="item"><img src="/assets/image_002.jpg" class="img-responsive" alt=""></div>
                    <div class="item"><img src="/assets/image_003.jpg" class="img-responsive" alt=""></div>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapibus ipsum eu, mattis urna.</p>
            <div class="post-info">
                <span>Posted by: admin</span>
                <a href="single.html" class="btn btn-inverse">View More</a>
            </div>
        </div>
    </article>
    <!-- POST - END -->
    
    <!-- POST - START --
    <article class="post">
        <div class="post-date-wrapper">
            <div class="post-date">
                <div class="day">25</div>
                <div class="month">Jan 2014</div>
            </div>
            <div class="post-type">
                <i class="fa fa-photo"></i>
            </div>
        </div>
        <div class="post-body">
            <h2>Blog post with Soundcloud</h2>
            <div class="flex-video soundcloud">
                <iframe height="166" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/122756510&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapibus ipsum eu, mattis urna.</p>
            <div class="post-info">
                <span>Posted by: admin</span>
                <a href="single.html" class="btn btn-inverse">View More</a>
            </div>
        </div>
    </article>
    <!-- POST - END -->
    
    <!-- POST - START --
    <article class="post">
        <div class="post-date-wrapper">
            <div class="post-date">
                <div class="day">25</div>
                <div class="month">Jan 2014</div>
            </div>
            <div class="post-type">
                <i class="fa fa-font"></i>
            </div>
        </div>
        <div class="post-body">
            <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et.</h2>
            <div class="flex-video widescreen"><iframe width="1280" height="720" src="https://www.youtube.com/embed/ZgYWkbMRhz8?rel=0" allowfullscreen></iframe></div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapibus ipsum eu, mattis urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapiis urna.</p>
            <div class="post-info">
                <span>Posted by: admin</span>
                <a href="single.html" class="btn btn-inverse">View More</a>
            </div>
        </div>
    </article>
    <!-- POST - END -->
    
</div>
<!--
<ul class="pagination">
    <li class="disabled"><a href="#"><i class="fa fa-angle-left"></i></a></li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
</ul>

app/views/home/send_contact.html.erb
Mensaje Enviado

app/views/home/services.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Nosotros</div>
  <div class="panel-body">
    Facilitar la organización de las actividades de entretenimiento tecnológicas 
  </div>
</div>

app/views/home/single.html.erb
<!-- CONTENT BODY - START -->
<div class="col-sm">
	<div class="box">
                            
        <!-- POST - START -->
        <article class="post post-single">
        	<div class="post-date-wrapper">
            	<div class="post-date">
                	<div class="day">9</div>
                	<div class="month">Nov 2014</div>
                </div>
                <div class="post-type">
                	<i class="fa fa-video-camera"></i>
                </div>
            </div>
            <div class="post-body">
                <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et.</h2>
                <div class="flex-video widescreen"><iframe width="420" height="315" src="https://www.youtube.com/embed/U1p9ZqGOY9Y" frameborder="0" allowfullscreen></iframe></div>
                <p>En la primera version de Duoc League of Legends por parte del
            equipo de estudiantes quienes llevaron a cabo este evento junto con el apoyo de Duoc, se contemplaron torneos de Counter-Strike 1.6,
            League of Legends y un torneo de Cosplay.</p>
                <!--<p>Proin arcu nulla, accumsan vel lacinia a, sodales eget nulla. Duis condimentum tristique risus ut consequat. Integer sollicitudin urna lectus, nec auctor nisl aliquam nec. Fusce consequat purus eget massa laoreet, vel sollicitudin sapien scelerisque. Nunc efficitur commodo nibh, ut accumsan elit sodales nec.</p>
                <p><img src="assets/image_001.jpg" class="pull-left" style="max-width:300px;" alt=""> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapibus ipsum eu, mattis urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere magna a dapibus luctus. Curabitur posuere vel nisi et scelerisque. Praesent imperdiet sed enim et ornare. In congue quis enim ut gravida. Aenean non justo varius, dapibus ipsum eu, mattis urna.</p>-->
                <div class="post-info">
                    <span>Posted by: admin</span>
                    <a href="#respond" class="btn btn-primary scroll">Add comment</a>
                </div>
            </div>
        </article>
        <!-- POST - END -->
        
        <!-- COMMENT WRAPPER - START --
        
        <div class="comments">
            <h2>3 Comments</h2>
            <ol class="commentlist">
            	
                <!-- COMMENT - START --
                <li class="comment">
                    <div class="avatar"><img src="assets/user.jpg" alt=""></div>
                    <div class="comment-body">
                        <div class="author">
                            <h3>John Doe</h3>
                            <div class="meta"><span class="date" title="2015-01-29 20:16:04">2015-01-29 20:16:04</span></div>
                        </div>      
                        <p class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et.</p>
                        <div class="reply"><a href=""><i class="fa fa-reply"></i>Reply</a></div>
                    </div>
                    
                    <ul class="children">
                    	<!-- COMMENT - START --
                        <li class="comment">
                            <div class="avatar"><img src="assets/user.jpg" alt=""></div>
                            <div class="comment-body">
                                <div class="author">
                                    <h3>John Doe</h3>
                                    <div class="meta"><span class="date" title="2015-01-29 20:16:04">2015-01-29 20:16:04</span></div>
                                </div>      
                                <p class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et.</p>
                                <div class="reply"><a href=""><i class="fa fa-reply"></i>Reply</a></div>
                            </div>
                        </li>
                        <!-- COMMENT - END -->
                        
                        <!-- COMMENT - START --
                        <li class="comment">
                            <div class="avatar"><img src="assets/user.jpg" alt=""></div>
                            <div class="comment-body">
                                <div class="author">
                                    <h3>John Doe</h3>
                                    <div class="meta"><span class="date" title="2015-01-29 20:16:04">2015-01-29 20:16:04</span></div>
                                </div>      
                                <p class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et.</p>
                                <div class="reply"><a href=""><i class="fa fa-reply"></i>Reply</a></div>
                            </div>
                        </li>
                        <!-- COMMENT - END -->
                    </ul>
                    
                </li>
                <!-- COMMENT - END -->
                
                <!-- COMMENT - START --
                <li class="comment">
                    <div class="avatar"><img src="assets/user.jpg" alt=""></div>
                    <div class="comment-body">
                        <div class="author">
                            <h3>John Doe</h3>
                            <div class="meta"><span class="date" title="2015-01-29 20:16:04">2015-01-29 20:16:04</span></div>
                        </div>      
                        <p class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et.</p>
                        <div class="reply"><a href=""><i class="fa fa-reply"></i>Reply</a></div>
                    </div>
                </li>
            	<!-- COMMENT - END -->
                
            </ol>    
        </div>
        <!-- COMMENT WRAPPER - START --
        
       	<!-- COMMENT FORM - END --
        <div id="respond" class="comment-respond">
			<h3 id="reply-title" class="comment-reply-title">Write a comment</h3>
			<form method="post" id="commentform" class="comment-form">
                <div class="form-group comment-form-author">
                    <label for="author">Name<span class="required">*</span></label>
                    <input class="form-control" id="author" name="author" type="text" value="">
                </div>
                <div class="form-group comment-form-email">
                    <label for="email">Email<span class="required">*</span></label>
                    <input class="form-control" id="email" name="email" type="email" value="">
                </div>
				<div class="form-group comment-form-comment">
                    <label for="comment">Comment<span class="required">*</span></label>
                    <textarea class="form-control" id="comment" name="comment" aria-required="true"></textarea>
                </div>												
				<button class="btn btn-primary" type="submit">Submit</button>					
        	</form>
		</div>
        <!-- COMMENT FORM - END --
        
    </div>-->
</div>
<!-- CONTENT BODY - END -->
            
        </div>
    </section>
</div>
<!-- ==========================
	CONTENT - END 
=========================== -->

	<!-- ==========================
	FOOTER - START 
=========================== -->
<div class="container">
	<div class="footer-boxes">
    	<div class="row">
                    
            <!-- FOOTER BOX - START -->
        	<div class="col-md-4 hidden-xs hidden-sm">
            	<div class="box">
                	<h4>About Us</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac.</p>
                </div>
        	</div>
            <!-- FOOTER BOX - END -->
            
            <!-- FOOTER BOX - START -->
            <div class="col-sm-6 col-md-4">
            	<div class="box footer-tags">
					<h4>Tags</h4>
                    <a href=""><span class="text-10">Clean</span></a>
                    <a href=""><span class="text-20">CV</span></a>
                    <a href=""><span class="text-20">Flat</span></a>
                    <a href=""><span class="text-14">Freelance</span></a>
                    <a href=""><span class="text-20">Modern</span></a>
                    <a href=""><span class="text-12">One Page</span></a>
                    <a href=""><span class="text-14">Professional</span></a>
                    <a href=""><span class="text-14">Responsive</span></a>
                    <a href=""><span class="text-16">Resume</span></a>
                    <a href=""><span class="text-20">Business</span></a>
                    <a href=""><span class="text-16">Corporate</span></a>
                    <a href=""><span class="text-18">CSS3</span></a>
                    <a href=""><span class="text-12">HTML5</span></a>
                    <a href=""><span class="text-16">Mobile First</span></a>
                    <a href=""><span class="text-20">Multipurpose</span></a>
                    <a href=""><span class="text-14">Portfolio</span></a>                   
				</div>
        	</div>
            <!-- FOOTER BOX - END -->
            
            <!-- FOOTER BOX - START -->
            <div class="col-sm-6 col-md-4 hidden-xs">
            	<div class="box footer-posts">
                    <h4>Recent Posts</h4>	
                    <ul class="list-unstyled">
                        <li><a href="#">Pellentesque habitant morbi</a> <span class="post-date">6.2.2015</span></li>
                        <li><a href="#">Tristique senectus et netus</a> <span class="post-date">31.1.2015</span></li>
                        <li><a href="#">Et malesuada fames ac</a> <span class="post-date">9.12.2014</span></li>
                        <li><a href="#">Turpis egestas nullam</a> <span class="post-date">1.12.2014</span></li>
                        <li><a href="#">Posuere magna a dapibus luctus</a> <span class="post-date">25.11.2014</span></li>
                    </ul>
                </div>
        	</div>
            <!-- FOOTER BOX - END -->
            
        </div>
    </div>
	<footer class="navbar navbar-default">
    	<div class="row">
        	<div class="col-md-6 hidden-xs hidden-sm">
            	<ul class="nav navbar-nav">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="team.html">Admin team</a></li>
                    <li><a href="profile.html">Profile</a></li>
                    <li><a href="tournament.html">Tournament</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="forum.html">Forum</a></li>
                </ul>
            </div>
            <div class="col-md-6">
            	<p class="copyright">© Progaming 2015 All right reserved. Designed by <a href="http://pixelized.cz/" target="_blank">Pixelized Studio.</a></p>
            </div>
        </div>
    </footer>
</div>
<!-- ==========================
	FOOTER - END 
=========================== -->