config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users, controllers: { registrations: "users/registrations" }

  

  get '/admin', to: 'admin/home#index'

  namespace :admin do
    resources :users
    resources :games
    resources :teams
  end
  root "home#index"
  get "/contacto",to: "home#contact", as: 'contact'
  post "send_contact", to: "home#send_contact"
  get "/nosotros", to: "home#about", as: 'about'
  get "/servicios", to: "home#services", as: 'services'
  get "/torneos", to: "home#tournaments", as:'tournaments'
  get "/single", to: "home#single", as: 'single'

end

app/views/layouts/_footer.html.erb
    <div class="container">
        <div class="footer-boxes">
            <div class="row">
                        
                <!-- FOOTER BOX - START -->
                <div class="col-md-4 hidden-xs hidden-sm">
                    <div class="box">
                        <h4>About Us</h4>
                        <p>Nuestra misión es producir y facilitar la organización de las actividades de entretenimiento tecnológicas, mediante softwares construidos por nuestro propio equipo de informática. Nuestra visión es incentivar nacionalmente el mercado tecnológico y los deportes electrónicos. Nombre del software BETA: Zarit.</p>
                    </div>
                </div>
                <!-- FOOTER BOX - END -->
                
                <!-- FOOTER BOX - START -->
                <div class="col-sm-6 col-md-4">
                    <div class="box footer-tags">
                        <h4>Tags</h4>
                        <a href=""><span class="text-10">Clean</span></a>
                        <a href=""><span class="text-20">CV</span></a>
                        <a href=""><span class="text-20">Flat</span></a>
                        <a href=""><span class="text-14">Freelance</span></a>
                        <a href=""><span class="text-20">Modern</span></a>
                        <a href=""><span class="text-12">One Page</span></a>
                        <a href=""><span class="text-14">Professional</span></a>
                        <a href=""><span class="text-14">Responsive</span></a>
                        <a href=""><span class="text-16">Resume</span></a>
                        <a href=""><span class="text-20">Business</span></a>
                        <a href=""><span class="text-16">Corporate</span></a>
                        <a href=""><span class="text-18">CSS3</span></a>
                        <a href=""><span class="text-12">HTML5</span></a>
                        <a href=""><span class="text-16">Mobile First</span></a>
                        <a href=""><span class="text-20">Multipurpose</span></a>
                        <a href=""><span class="text-14">Portfolio</span></a>                   
                    </div>
                </div>
                <!-- FOOTER BOX - END -->
                
                <!-- FOOTER BOX - START -->
                <div class="col-sm-6 col-md-4 hidden-xs">
                    <div class="box footer-posts">
                        <h4>Recent Posts</h4>   
                        <ul class="list-unstyled">
                            <li><a href="#">Pellentesque habitant morbi</a> <span class="post-date">6.2.2015</span></li>
                            <li><a href="#">Tristique senectus et netus</a> <span class="post-date">31.1.2015</span></li>
                            <li><a href="#">Et malesuada fames ac</a> <span class="post-date">9.12.2014</span></li>
                            <li><a href="#">Turpis egestas nullam</a> <span class="post-date">1.12.2014</span></li>
                            <li><a href="#">Posuere magna a dapibus luctus</a> <span class="post-date">25.11.2014</span></li>
                        </ul>
                    </div>
                </div>
                <!-- FOOTER BOX - END -->
                
            </div>
        </div>
    <footer class="navbar navbar-default">
        <div class="row">
            <div class="col-md-6 hidden-xs hidden-sm">
                <ul class="nav navbar-nav">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="team.html">Admin team</a></li>
                    <li><a href="profile.html">Profile</a></li>
                    <li><a href="tournament.html">Tournament</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="forum.html">Forum</a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <p class="copyright">© Progaming 2015 All right reserved. Designed by <a href="http://pixelized.cz/" target="_blank">Pixelized Studio.</a></p>
            </div>
        </div>
    </footer>
</div>

app/views/layouts/_jumbotron.html.erb
 <div class="container">
        <div class="jumbotron">
            <div class="jumbotron-panel">
                <div class="panel panel-primary collapse-horizontal">
                    <a data-toggle="collapse" class="btn btn-primary collapsed" data-target="#toggle-collapse">Check our Servers </a>
                    <div class="jumbotron-brands">
                        <ul class="brands brands-sm brands-inline brands-circle">
                            <li><a href="https://www.facebook.com/DuocLeagueOfGamers"><i class="fa fa-facebook"></i></a></li>
                            <li><a href=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href=""><i class="fa fa-twitch"></i></a></li>
                            <li><a href=""><i class="fa fa-steam"></i></a></li>
                        </ul>
                    </div>
                    <!--<div id="toggle-collapse" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table table-bordered table-header">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Name</th>
                                        <th>IP Address</th>
                                        <th>Map</th>
                                        <th>Players</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><img src="/assets/csgo.jpg" alt=""></td>
                                        <td>[EU] CS:GO #1 | pixelized.cz</td>
                                        <td>123.221.45.12:29999</td>
                                        <td>de_dust2</td>
                                        <td>18/18</td>
                                    </tr>
                                    <tr>
                                        <td><img src="/assets/csgo.jpg" alt=""></td>
                                        <td>[CZ/SK] CS:GO Public | pixelized.cz</td>
                                        <td>45.184.170.200:27851</td>
                                        <td>de_inferno</td>
                                        <td>24/32</td>
                                    </tr>
                                    <tr>
                                        <td><img src="/assets/lol.png" alt=""></td>
                                        <td>[EU] League of Legends</td>
                                        <td>50.243.180.246:25429</td>
                                        <td>normal</td>
                                        <td>10/30</td>
                                    </tr>
                                    <tr>
                                        <td><img src="/assets/gta.png" alt=""></td>
                                        <td>[EU] GTA Server</td>
                                        <td>132.24.45.83:27852</td>
                                        <td>classic</td>
                                        <td>22/60</td>
                                    </tr>                               
                                </tbody>
                            </table>
                        </div>
                    </div>-->
                </div>
            </div>
            
            <div id="jumbotron-slider">
                
                <!-- JUMBOTRON ITEM - START -->       
                <div class="item">
                    <a href="single.html">
                        <div class="overlay-wrapper">
                            <img src="/assets/image_001.jpg" class="img-responsive" alt="">
                            <span class="overlay"></span>
                            <h2>DLG 2014<span>9 Noviembre 2014</span></h2>
                        </div>
                    </a>
                </div>
                <!-- JUMBOTRON ITEM - END -->     
                
                <!-- JUMBOTRON ITEM - START -->     
                <div class="item">
                    <a href="single.html">
                        <div class="overlay-wrapper">
                            <img src="/assets/image_002.jpg" class="img-responsive" alt="">
                            <span class="overlay"></span>
                            <h2>DLG 2014<span>9 Noviembre 2014</span></h2>
                        </div>
                    </a>
                </div>
                <!-- JUMBOTRON ITEM - END -->     
                
                <!-- JUMBOTRON ITEM - START -->     
                <div class="item">
                    <a href="single.html">
                        <div class="overlay-wrapper">
                            <img src="/assets/image_003.jpg" class="img-responsive" alt="">
                            <span class="overlay"></span>
                            <h2>DLG 2014<span>9 Noviembre 2014</span></h2>
                        </div>
                    </a>
                </div>
                <!-- JUMBOTRON ITEM - END -->     
                
                <!-- JUMBOTRON ITEM - START -->     
                <div class="item">
                    <a href="single.html">
                        <div class="overlay-wrapper">
                            <img src="/assets/image_004.jpg" class="img-responsive" alt="">
                            <span class="overlay"></span>
                            <h2>Lorem Ipsum dolor<span>27 March 2014</span></h2>
                        </div>
                    </a>
                </div>
                <!-- JUMBOTRON ITEM - END -->     
                
                <!-- JUMBOTRON ITEM - START -->     
                <div class="item">
                    <a href="single.html">
                        <div class="overlay-wrapper">
                            <img src="/assets/image_005.jpg" class="img-responsive" alt="">
                            <span class="overlay"></span>
                            <h2>Lorem Ipsum dolor<span>27 March 2014</span></h2>
                        </div>
                    </a>
                </div>
                <!-- JUMBOTRON ITEM - END -->     
                
            </div>
        </div>
    </div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="index.html" class="navbar-brand visible-xs">Progaming</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><%= link_to 'Inicio',root_path%></li>
                <li><%= link_to 'Nosotros',about_path%></li>
                <li><%= link_to 'Torneos',tournaments_path%></li>
                <li><%= link_to 'Contacto',contact_path%></li>
              
                <!--<li><a href="gallery.html">Gallery</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gaming</a>
                    <ul class="dropdown-menu">
                        <li><a href="gaming-team.html"><i class="fa fa-plus"></i>Gaming team</a></li>
                        <li><a href="matches-list.html"><i class="fa fa-plus"></i>List of matches</a></li>
                        <li><a href="match-single.html"><i class="fa fa-plus"></i>Single match</a></li>
                        <li><a href="tournament.html"><i class="fa fa-plus"></i>Tournament</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Forum</a>
                    <ul class="dropdown-menu">
                        <li><a href="forum.html"><i class="fa fa-plus"></i>Forum Page</a></li>
                        <li><a href="forum-list.html"><i class="fa fa-plus"></i>Forum threads</a></li>
                        <li><a href="forum-single.html"><i class="fa fa-plus"></i>Single forum post</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages</a>
                    <ul class="dropdown-menu">
                        <li><a href="signup.html"><i class="fa fa-plus"></i>Sign up</a></li>
                        <li><a href="signin.html"><i class="fa fa-plus"></i>Sign in</a></li>
                        <li><a href="servers.html"><i class="fa fa-plus"></i>Servers</a></li>
                        <li><a href="404.html"><i class="fa fa-plus"></i>Error Page</a></li>
                    </ul>
                </li>-->
            </ul>
            <div class="pull-right navbar-buttons hidden-xs">
                <% if !current_user %>
                    <%= link_to 'Registrarse', new_user_registration_path, class: 'btn btn-primary' %>
                    
                    <%= link_to 'Iniciar Sesion', new_user_session_path, class: 'btn btn-inverse' %>
                <% else %>
                    <a href="#" class="dropdown-toggle btn btn-inverse" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name%>  <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <% if current_user.is_admin %>
                            <li> <a href="/admin"> Seccion admin </a></li>
                        <% end %>
                        <li><%= link_to "Perfil", edit_user_registration_path(current_user) %> </li>
                        <li><%= link_to "Salir", destroy_user_session_path, method: :delete %> </li>
                    </ul>
                <% end %>
                <!-- <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-inverse' %>-->
                <a class="navbar-icon show2" id="open-search"><i class="fa fa-search"></i></a>
                <a class="navbar-icon hidden" id="close-search"><i class="fa fa-times"></i></a>
                <div class="hidden" id="navbar-search-form">
                    <form role="search">
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" value="" name="navbar-search" id="navbar-search" class="form-control" placeholder="Search">
                                <span class="input-group-btn"><button class="btn btn-primary" type="submit" id="navbar-search-submit"><i class="fa fa-search"></i></button></span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-4 hidden-xs">
                    
                    <!-- SIDEBAR BOX - START -->
                    <div class="box sidebar-box widget-wrapper">
                        <h3>Próximo Torneo</h3>
                        <div class="tournament">
                            <a href="tournament.html"><img src="/assets/dlg.png" class="img-responsive" alt=""></a>
                            <h4>DLG 2015</h4>
                            <p>¡Participa en Duoc League of Gamers 2015 inscribiendote junto a tu equipo!, así mismo si quieres participar en
                            Cosplay de DLG 2015</p>
                            <div class="date">25  - 31 Agosto 2015</div>
                            <div class="text-center"><a href="/torneos" class="btn btn-primary">Mas info</a></div>
                        </div>
                    </div>
                    <!-- SIDEBAR BOX - END -->
                    
                    <!-- SIDEBAR BOX - START -->
                    <div class="box sidebar-box widget-wrapper widget-matches">
                        <h3>Upcoming matches <a href="/torneos" class="btn btn-primary pull-right btn-sm">All matches</a></h3>
                        
                        <a href="match-single.html">
                            <table class="table match-wrapper">
                                <tbody>
                                    <tr>
                                        <td class="game">
                                            <img src="/assets/lol.png" alt="">
                                            <span>Lol</span>
                                        </td>
                                        <td class="game-date">
                                            <span>01/09/2015 - xx:xx</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/cze.png" alt="">Desconocido</td>
                                        <td class="team-score">-</td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/swe.png" alt="">Desconocido</td>
                                        <td class="team-score">-</td>
                                    </tr>
                                </tbody>
                            </table>
                        </a>
                        
                        <a href="match-single.html">
                            <table class="table match-wrapper">
                                <tbody>
                                    <tr>
                                        <td class="game">
                                            <img src="/assets/csgo.jpg" alt="">
                                            <span>CS GO</span>
                                        </td>
                                        <td class="game-date">
                                            <span>01/09/2015 - 22:00</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/den.png" alt="">Fnatic</td>
                                        <td class="team-score">-</td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/swe.png" alt="">Ninjas in Pyjamas</td>
                                        <td class="team-score">-</td>
                                    </tr>
                                </tbody>
                            </table>
                        </a>
                    </div>
                    <!-- SIDEBAR BOX - END -->
                    
                    <!-- SIDEBAR BOX - START -
                    <div class="box sidebar-box widget-wrapper widget-matches">
                        <h3>Latest matches <a href="matches-list.html" class="btn btn-primary pull-right btn-sm">All matches</a></h3>
                        
                        <a href="match-single.html">
                            <table class="table match-wrapper">
                                <tbody>
                                    <tr>
                                        <td class="game">
                                            <img src="/assets/lol.png" alt="">
                                            <span>LoL</span>
                                        </td>
                                        <td class="game-date">
                                            <span>18/02/2015 - 14:00</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/usa.png" alt=""><b>Ninjas in Pyjamas</b></td>
                                        <td class="team-score win">9</td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/den.png" alt="">Natus Vincere</td>
                                        <td class="team-score lose">5</td>
                                    </tr>
                                </tbody>
                            </table>
                        </a>
                        
                        <a href="match-single.html">
                            <table class="table match-wrapper">
                                <tbody>
                                    <tr>
                                        <td class="game">
                                            <img src="/assets/gta.png" alt="">
                                            <span>GTA</span>
                                        </td>
                                        <td class="game-date">
                                            <span>8/6/2015 - 12:00</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/swe.png" alt=""><b>Ninjas in Pyjamas</b></td>
                                        <td class="team-score win">9</td>
                                    </tr>
                                    <tr>
                                        <td class="team-name"><img src="/assets/usa.png" alt="">Natus Vincere</td>
                                        <td class="team-score lose">5</td>
                                    </tr>
                                </tbody>
                            </table>
                        </a>
                    </div>
                    <!-- SIDEBAR BOX - END -->
                    
                    <!-- SIDEBAR BOX - START 
                    <div class="box sidebar-box widget-wrapper">
                        <h3>Categories</h3>
                        <ul class="nav nav-sidebar">
                            <li><a href="#">Tournaments<span>45</span></a></li>
                            <li><a href="#">Leagues<span>122</span></a></li>
                            <li><a href="#">Counter Strike<span>684</span></a></li>
                            <li><a href="#">Dota 2<span>1242</span></a></li>
                            <li><a href="#">World of Warcraft<span>112</span></a></li>
                            <li><a href="#">Minecraft<span>18</span></a></li>
                        </ul>
                    </div>
                    <!-- SIDEBAR BOX - END -->
                    
                    <!-- SIDEBAR BOX - START 
                    <div class="box sidebar-box widget-wrapper">
                        <h3>Latest Tweets</h3>
                        <div id="twitter-wrapper">
                        </div>
                    </div>
                    <!-- SIDEBAR BOX - END -->
                    
                </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
        Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- ==========================
        Title 
    =========================== -->
    <title>Duoc League of Legends</title>
        
    <!-- ==========================
        Fonts 
    =========================== -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <!-- ==========================
        CSS 
    =========================== -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/animate.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
    <link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="/assets/custom.css" rel="stylesheet" type="text/css">
    
    <!-- ==========================
        JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>
    <h1>progaming</h1>
    
    <!-- ==========================
        HEADER - START 
    =========================== -->
    <%= render 'layouts/navbar' %>
    <!-- ==========================
        HEADER - END 
    =========================== -->  
    
    <!-- ==========================
        TITLE - START 
    =========================== -->
    <div class="container hidden-xs">
        <div class="header-title">
            <div class="pull-left">
                <h2><a href="/#"><span class="text-primary">Beta</span>Zarit</a></h2>
                <p>Torneos de videojuegos Chile</p>
            </div>
        </div>
    </div>
    <!-- ==========================
        TITLE - END 
    =========================== -->
    
    <!-- ==========================
        JUMBOTRON - START 
    =========================== -->
    <%= render 'layouts/jumbotron' %>
    <!-- ==========================
        JUMBOTRON - END 
    =========================== -->
    
    <!-- ==========================
        CONTENT - START 
    =========================== -->
    <div class="container">
        <section class="content-wrapper">
            <div class="row">
            
                <!-- SIDEBAR - START -->
                <%= render 'layouts/sidebar' %>
                <!-- SIDEBAR - END -->
                
                <!-- CONTENT BODY - START -->
                <div class="col-sm-8">
                    <%= yield %>
                </div>
                <!-- CONTENT BODY - END -->
                
            </div>
        </section>
    </div>
    <!-- ==========================
        CONTENT - END 
    =========================== -->
   
    <!-- ==========================
        FOOTER - START 
    =========================== -->
    <%= render 'layouts/footer' %>
    <!-- ==========================
        FOOTER - END 
    =========================== -->
   
    <!-- ==========================
        JS 
    =========================== -->        
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/owl.carousel.js"></script>
    <script src="/assets/jquery.magnific-popup.min.js"></script>
    <script src="/assets/creative-brands.js"></script>
    <script src="/assets/jquery.vegas.min.js"></script>
    <script src="/assets/twitterFetcher_min.js"></script>
    <script src="/assets/jquery.countdown.min.js"></script>
    <script src="/assets/custom.js"></script>
</body>
</html>